fix: allow parsing exports of undeclared variables
decaffeinate cannot update to the latest `add-variable-declarations` because its version of `@babel/parser` is more restrictive about export bindings, resulting in these failures:

```
  1) imports
       handles ES module export binding list:
     Error: AddVariableDeclarationsStage failed to parse: Export 'a' is not defined (1:8)
      at new PatchError (src/utils/PatchError.ts:6:5)
      at makePatchError (src/utils/resolveToPatchError.ts:12:5)
      at Object.resolveToPatchError [as default] (src/utils/resolveToPatchError.ts:24:12)
      at runStage (src/index.ts:111:41)
      at /Users/donovan/src/decaffeinate/src/index.ts:100:9
      at Array.forEach (<anonymous>)
      at runStages (src/index.ts:99:10)
      at Object.convert (src/index.ts:73:16)
      at checkOutput (test/support/check.ts:58:21)
      at Object.check [as default] (test/support/check.ts:18:3)
      at Context.<anonymous> (test/import_test.ts:143:10)

  2) imports
       handles ES module export binding list on multiple lines without separators:
     Error: AddVariableDeclarationsStage failed to parse: Export 'a' is not defined (2:2)
      at new PatchError (src/utils/PatchError.ts:6:5)
      at makePatchError (src/utils/resolveToPatchError.ts:12:5)
      at Object.resolveToPatchError [as default] (src/utils/resolveToPatchError.ts:24:12)
      at runStage (src/index.ts:111:41)
      at /Users/donovan/src/decaffeinate/src/index.ts:100:9
      at Array.forEach (<anonymous>)
      at runStages (src/index.ts:99:10)
      at Object.convert (src/index.ts:73:16)
      at checkOutput (test/support/check.ts:58:21)
      at Object.check [as default] (test/support/check.ts:18:3)
      at Context.<anonymous> (test/import_test.ts:154:10)
```